In [2]:
import pandas as pd
import os

In [3]:
DATA_DIR = "../Data"
OUTPUT_DIR = "../Merged_Olist_Data"
os.makedirs(OUTPUT_DIR, exist_ok=True)

Loading CSV Files

In [4]:
df_orders    = pd.read_csv(os.path.join(DATA_DIR, "olist_orders_dataset.csv"))
df_reviews   = pd.read_csv(os.path.join(DATA_DIR, "olist_order_reviews_dataset.csv"))
df_customers = pd.read_csv(os.path.join(DATA_DIR, "olist_customers_dataset.csv"))
df_products  = pd.read_csv(os.path.join(DATA_DIR, "olist_products_dataset.csv"))


print(f"Orders:    {df_orders.shape}")
print(f"Reviews:   {df_reviews.shape}")
print(f"Customers: {df_customers.shape}")
print(f"Products:  {df_products.shape}")

Orders:    (99441, 8)
Reviews:   (99224, 7)
Customers: (99441, 5)
Products:  (32951, 9)

In [5]:
df_products.head()




df_orders.head()
df_reviews.head()
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [6]:
df_reviews = (df_reviews
              .sort_values("review_creation_date")
              .drop_duplicates("order_id", keep="last"))

df_merged = df_orders.merge(df_reviews, on="order_id", how="left")

In [7]:
df_merged = df_merged.merge(df_customers, on="customer_id", how="left")

In [8]:
print(f"Original orders row count : {len(df_orders)}")
print(f"After joins row count     : {len(df_merged)}")

if len(df_merged) == len(df_orders):
    print("Row count matches")
else:
    diff = len(df_merged) - len(df_orders)
    print(f"Row count increased by {diff}")

Original orders row count : 99441
After joins row count     : 99441
Row count matches

In [9]:
print("Shape:", df_merged.shape)
print("Columns:", df_merged.columns.tolist())
df_merged.head()

Shape: (99441, 18)
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'review_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,359d03e676b3c069f62cadba8dd3f6e8,5.0,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,e50934924e227544ba8246aeb3770dd4,5.0,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [10]:
output_path = os.path.join(OUTPUT_DIR, "master_orders.csv")
df_merged.to_csv(output_path, index=False)
print(f"master_orders.csv saved to {output_path}")

master_orders.csv saved to Merged_Olist_Data\master_orders.csv

In [11]:
master_csv  = pd.read_csv(os.path.join(OUTPUT_DIR, "master_orders.csv"))
print(f": master_orders.csv   {master_csv.shape}")

: master_orders.csv   (99441, 18)

In [12]:
master_csv.duplicated().sum()

np.int64(0)

In [13]:
print(master_csv["order_id"].nunique())

99441